name: Dev build and publish Python distributions to PyPI

on:
  push:
    branches-ignore:
      - master

jobs:
  build-n-publish:
    name: Dev build and Python distributions to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          pip install -U pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "PATH="${PATH}:/root/.poetry/bin"" >> $GITHUB_ENV
      # Prepare custom build version
      - name: Get package version
        id: pack_ver
        run: echo '::set-output name=package_version::$(poetry version -s)'
      - name: Build custom package version
        id: release_ver
        run: echo ::set-output name=value::"${{ steps.pack_ver.outputs.package_version }}.dev${{ github.run_id }}"
      - name: Show package version
        run: echo ${{ steps.release_ver.outputs.value }}
      - name: Set version for current build in pyproject.toml
        run: poetry version ${{ steps.release_ver.outputs.value }}
      # Build and publish
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build package
        run: poetry build
      # - name: Publish distribution to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     user: __token__
      #     password: ${{ secrets.TEST_PYPI_PASSWORD }}
      #     repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/