name: MyPy & flake8 checks

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        pip install mypy
        python3 -m pip install types-protobuf
        
        flake8_plugins="
          flake8==4.0.1
          flake8-bugbear==22.7.1
          flake8-builtins==1.5.3
          flake8-comprehensions==3.10.0
          flake8-eradicate==1.2.1
          flake8-fixme==1.1.1
          flake8-multiline-containers==0.0.19
          flake8-print==5.0.0
          flake8-return==1.1.3
          flake8-quotes==3.3.1
          flake8-simplify==0.19.2
          pep8-naming==0.13.1
          flake8-expression-complexity==0.0.11
          flake8-import-order==0.18.1
          flake8-annotations-complexity==0.0.7
          flake8-annotations-coverage==0.0.6
        "
        pip install $flake8_plugins
    - name: Run MyPy
      continue-on-error: true
      run: mypy .
    - name: Run flake8
      run: flake8 .
